services:
  internal-api:
    build:
      context: .
      dockerfile: Acme.InternalApiStub/Dockerfile
    container_name: internal-api
    ports:
      - "5009:5159"

  mcp-server:
    build:
      context: .
      dockerfile: Acme.McpServer/Dockerfile
    container_name: mcp-server
    depends_on:
      - internal-api
    ports:
      - "3004:3004"
